"""Initial migration

Revision ID: aeba939c82e9
Revises: 
Create Date: 2025-04-03 13:17:21.010673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aeba939c82e9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_feriado_holiday_id', table_name='feriado')
    op.drop_table('feriado')
    op.drop_index('ix_combination_combination_rule_id', table_name='combination')
    op.drop_table('combination')
    op.drop_index('ix_combination_rules_id', table_name='combination_rules')
    op.drop_table('combination_rules')
    op.drop_index('ix_schedule_deviation_schedule_deviation_id', table_name='schedule_deviation')
    op.drop_table('schedule_deviation')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule_deviation',
    sa.Column('schedule_deviation_id', sa.INTEGER(), server_default=sa.text("nextval('schedule_deviation_schedule_deviation_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('before_shift', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('after_shift', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('requires_approval', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('unplanned', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('schedule_deviation_id', name='schedule_deviation_pkey'),
    sa.UniqueConstraint('name', name='schedule_deviation_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_schedule_deviation_schedule_deviation_id', 'schedule_deviation', ['schedule_deviation_id'], unique=False)
    op.create_table('combination_rules',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('combination_rule_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('schedule_deviation_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['combination_rule_id'], ['combination.combination_rule_id'], name='combination_rules_combination_rule_id_fkey'),
    sa.ForeignKeyConstraint(['schedule_deviation_id'], ['schedule_deviation.schedule_deviation_id'], name='combination_rules_schedule_deviation_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='combination_rules_pkey')
    )
    op.create_index('ix_combination_rules_id', 'combination_rules', ['id'], unique=False)
    op.create_table('combination',
    sa.Column('combination_rule_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('default', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('combination_rule_id', name='combination_pkey'),
    sa.UniqueConstraint('name', name='combination_name_key')
    )
    op.create_index('ix_combination_combination_rule_id', 'combination', ['combination_rule_id'], unique=False)
    op.create_table('feriado',
    sa.Column('holiday_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('public_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('year', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_renounceable', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_local', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('start', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('end', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('enable', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('holiday_id', name='feriado_pkey')
    )
    op.create_index('ix_feriado_holiday_id', 'feriado', ['holiday_id'], unique=False)
    # ### end Alembic commands ###
